### ISSUE TITLE
Issue with infinitive infinite loop while fetching data from api

### ISSUE THREAD

**Issue by hryndi** [hryndi/recipe_app_react#4]
I have a problem with putting data from an API into the state "dataArr". I want to fetch my recipe data again only when the user stops typing (in my case, I implemented it with a timeout for 1 second). The data should be set to the "dataArr" state initially and be loaded only when the user starts typing something in the input bar and then stops after one second. In my case, if I try to set my data to an array value, I get into an infinite loop and it breaks. All logic is placed in a custom hook called UseRecipe. Thank you all for your time.

**Comment by I-Vishal-Kumar** [comment]
Hey assign it to me , I can handle this issue.

**Comment by hryndi** [comment]
@I-Vishal-Kumar 

Thank you for your help, It was really usefull for me. I no longer have an infinite loop, but I`ve noticet, than you removed my debounce loader, that was emplemented with setTimeout. I'm still getting an empty array initially, even when I have an initial value. My response with initial search word seams to be ok, but it is not pushing enything in array initial. Do you know what could be causing this?

![image](https://github.com/hryndi/recipe_app_react/assets/150298186/9fdda333-f06d-43ec-8fc1-0c8cb7cfd9f7)

![image](https://github.com/hryndi/recipe_app_react/assets/150298186/7ef093cd-e8fe-40db-b2e6-018a299747eb)

**Comment by I-Vishal-Kumar** [comment]
Its because of strict mode react uses strict mode for development environment which makes the useEffect mount -> dismount and then mount again thats why you are getting empty array

As for the debounce function I would like to draw your attention towards npm package useDebounce. Its good .
